# Generated by Django 2.2.1 on 2019-06-13 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activties', models.CharField(blank=True, max_length=200, null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('modver_datetime', models.DateTimeField(blank=True, default='9999-12-31 00:00:00', null=True)),
                ('original_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 't_activity',
            },
        ),
        migrations.CreateModel(
            name='ActivtiesDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.BigIntegerField(blank=True, null=True)),
                ('phonenumber_status', models.BooleanField(blank=True, default=False, null=True)),
                ('website', models.CharField(blank=True, max_length=300, null=True)),
                ('website_status', models.BooleanField(blank=True, null=True)),
                ('descripiton', models.TextField(blank=True, null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('modver_datetime', models.DateTimeField(blank=True, default='9999-12-31 00:00:00', null=True)),
                ('original_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by_id', models.CharField(blank=True, max_length=100, null=True)),
                ('activties', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Activties')),
            ],
            options={
                'db_table': 't_activity_detail',
            },
        ),
        migrations.CreateModel(
            name='CompanyActivties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activties', models.CharField(blank=True, max_length=200, null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('modver_datetime', models.DateTimeField(blank=True, default='9999-12-31 00:00:00', null=True)),
                ('original_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 't_comapany_activity',
            },
        ),
        migrations.CreateModel(
            name='CompanyActivtiesDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.BigIntegerField(blank=True, null=True)),
                ('phonenumber_status', models.BooleanField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=300, null=True)),
                ('website_status', models.BooleanField(blank=True, null=True)),
                ('descripiton', models.TextField(blank=True, null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('modver_datetime', models.DateTimeField(blank=True, default='9999-12-31 00:00:00', null=True)),
                ('original_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by_id', models.CharField(blank=True, max_length=100, null=True)),
                ('activties', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.CompanyActivties')),
            ],
            options={
                'db_table': 't_company_activity_detail',
            },
        ),
        migrations.CreateModel(
            name='LegelEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('modver_datetime', models.DateTimeField(blank=True, default='9999-12-31 00:00:00', null=True)),
                ('original_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 't_legelentity',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profiles_pic/')),
                ('companyname', models.CharField(blank=True, max_length=100, null=True)),
                ('companyname_status', models.BooleanField(blank=True, default=False, null=True)),
                ('legalentitytype_status', models.BooleanField(blank=True, default=False, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('city_status', models.BooleanField(blank=True, default=False, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('state_status', models.BooleanField(blank=True, default=False, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('country_status', models.BooleanField(blank=True, default=False, null=True)),
                ('postcode', models.CharField(blank=True, max_length=10, null=True)),
                ('postcode_status', models.BooleanField(blank=True, default=False, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('1', 'Published'), ('0', 'Unpublished')], max_length=100, null=True)),
                ('types', models.CharField(blank=True, choices=[('1', 'Profile'), ('0', 'CompanyProfile')], max_length=100, null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('modver_datetime', models.DateTimeField(blank=True, default='9999-12-31 00:00:00', null=True)),
                ('original_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by_id', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.ActivtiesDetail')),
                ('legalentitytype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.LegelEntity')),
                ('users', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_user_profile',
            },
        ),
        migrations.CreateModel(
            name='UserPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('modver_datetime', models.DateTimeField(blank=True, default='9999-12-31 00:00:00', null=True)),
                ('original_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by_id', models.CharField(blank=True, max_length=100, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Profile')),
            ],
            options={
                'db_table': 't_user_image',
            },
        ),
        migrations.CreateModel(
            name='ForgotCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('expiry_datetime', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_forgot_code',
            },
        ),
        migrations.CreateModel(
            name='CustomerImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField(null=True, verbose_name='Phone Number')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('modver_datetime', models.DateTimeField(blank=True, default='9999-12-31 00:00:00', null=True)),
                ('original_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'db_table': 't_customer_image',
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profiles_pic/')),
                ('companyname', models.CharField(blank=True, max_length=100, null=True)),
                ('companyname_status', models.BooleanField(blank=True, default=False, null=True)),
                ('legalentitytype', models.CharField(blank=True, max_length=100, null=True)),
                ('legalentitytype_status', models.BooleanField(blank=True, default=False, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('city_status', models.BooleanField(blank=True, default=False, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('street_status', models.BooleanField(blank=True, default=False, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('country_status', models.BooleanField(blank=True, default=False, null=True)),
                ('postcode', models.CharField(blank=True, max_length=10, null=True)),
                ('postcode_status', models.BooleanField(blank=True, default=False, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('1', 'Published'), ('0', 'Unpublished')], max_length=100, null=True)),
                ('types', models.CharField(blank=True, choices=[('1', 'Profile'), ('0', 'CompanyProfile')], max_length=100, null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('modver_datetime', models.DateTimeField(blank=True, default='9999-12-31 00:00:00', null=True)),
                ('original_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by_id', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.CompanyActivtiesDetail')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_company_profile',
            },
        ),
        migrations.CreateModel(
            name='CompanyImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('modver_datetime', models.DateTimeField(blank=True, default='9999-12-31 00:00:00', null=True)),
                ('original_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by_id', models.CharField(blank=True, max_length=100, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.CompanyProfile')),
            ],
            options={
                'db_table': 't_comapny_image',
            },
        ),
    ]
