# Generated by Django 2.2.1 on 2019-06-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=100, null=True, verbose_name='Phone Number'),
        ),
    ]
