# Generated by Django 2.2.1 on 2019-06-15 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190613_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='legalentitytype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.LegelEntity'),
        ),
    ]
