# Generated by Django 2.2.1 on 2019-06-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190615_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyimages',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='userpic',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
