# Generated by Django 2.2.1 on 2019-06-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190615_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyimages',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
